name: haxuvina
description: Haxuvina - Chúng tôi là giải pháp cuả bạn

publish_to: 'none' # Prevent accidental publish

version: 0.1.0+01

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.0
  flutter_localizations:
    sdk: flutter

  # Core & Utility
  intl: ^0.20.2
  crypto: ^3.0.6
  clipboard: ^0.1.3
  logging: ^1.0.2
  provider: ^6.0.0
  path_provider: ^2.0.11
  permission_handler: ^11.3.1
  share_plus: ^10.0.2
  shared_preferences: ^2.5.3
  shared_value: ^3.0.0
  rename: ^3.0.2

  # Firebase
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5

  # Google
  google_fonts: ^6.2.1
  google_sign_in: ^6.1.0
  google_maps_flutter: ^2.10.0
  geocoding: ^2.2.0
  location: ^5.0.3

  # UI
  badges: ^3.1.2
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  dotted_line: ^3.0.1
  dropdown_search: ^6.0.1
  expandable: ^5.0.1
  flip_card: ^0.7.0
  flutter_svg: ^2.0.6
  flutter_spinkit: ^5.1.0
  flutter_math_fork: ^0.7.1
  flutter_typeahead: ^5.2.0
  flutter_rating_bar: ^4.0.0
  flutter_chat_bubble: ^2.0.0
  flutter_html: ^3.0.0-beta.1
  flutter_countdown_timer: ^4.1.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_local_notifications: ^18.0.1
  fluttertoast: ^8.2.8
  shimmer: ^3.0.0
  photo_view: ^0.15.0
  timeline_list: ^0.0.3
  timeline_tile: ^2.0.0
  url_launcher: ^6.0.12
  route_transitions: ^2.0.1

  # Downloader, Picker, Platform
  file_picker: ^8.1.1
  image_picker: ^1.1.2
  flutter_downloader: ^1.8.3+2
  package_info_plus: ^8.1.2

  # Auth
  flutter_facebook_auth: ^7.0.1
  sign_in_with_apple: ^6.1.1

  # Validation
  validators: ^3.0.0
  intl_phone_number_input: ^0.7.0+2

  # Routing
  go_router: ^14.2.3
  one_context: ^4.0.0

  # JSON
  json_annotation: ^4.1.0

  open_filex: ^4.3.2

dependency_overrides:
  google_api_headers: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  json_serializable: ^6.2.0
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/htmls/
    - assets/fonts/
    - dummy_assets/
    - assets/flags/

  fonts:
    - family: BeVietnamPro
      fonts:
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-Thin.ttf
          weight: 100
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-Light.ttf
          weight: 300
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-Black.ttf
          weight: 900
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-BlackItalic.ttf
          weight: 900
          style: italic
    - family: PublicSansSerif
      fonts:
        - asset: assets/fonts/PublicSans-Regular.ttf
        - asset: assets/fonts/PublicSans-Bold.ttf
        - asset: assets/fonts/PublicSans-Medium.ttf
        - asset: assets/fonts/PublicSans-SemiBold.ttf
        - asset: assets/fonts/PublicSans-Italic.ttf
          style: italic
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Medium.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic
